version: '3'

services:
        chrony:
                build: ./chrony
                ports:
                        - 123
                privileged: true
                restart: always
                volumes:
                        - ./data:/data
